# permissions for end users to edit imagecaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-cache-operator
    app.kubernetes.io/managed-by: kustomize
  name: imagecache-editor-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - imagecaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - imagecaches/status
  verbs:
  - get
