# permissions for end users to view imagecaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-cache-operator
    app.kubernetes.io/managed-by: kustomize
  name: imagecache-viewer-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - imagecaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - imagecaches/status
  verbs:
  - get
